.mode tabs
.import Aiparms.txt Aiparms
.import Arena.txt Arena
.import armor.txt armor
.import ArmType.txt ArmType
.import automagic.txt automagic
.import AutoMap.txt AutoMap
.import belts.txt belts
.import bodylocs.txt bodylocs
.import books.txt books
.import charstats.txt charstats
.import CharTemplate.txt CharTemplate
.import colors.txt colors
.import Composit.txt Composit
.import cubemain.txt cubemain
.import cubemod.txt cubemod
.import cubetype.txt cubetype
.import difficultylevels.txt difficultylevels
.import ElemTypes.txt ElemTypes
.import experience.txt experience
.import gamble.txt gamble
.import gems.txt gems
.import hiredesc.txt hiredesc
.import hireling.txt hireling
.import HitClass.txt HitClass
.import inventory.txt inventory
.import itemratio.txt itemratio
.import ItemStatCost.txt ItemStatCost
.import ItemTypes.txt ItemTypes
.import Levels.txt Levels
.import lowqualityitems.txt lowqualityitems
.import LvlMaze.txt LvlMaze
.import LvlPrest.txt LvlPrest
.import LvlSub.txt LvlSub
.import LvlTypes.txt LvlTypes
.import LvlWarp.txt LvlWarp
.import MagicPrefix.txt MagicPrefix
.import MagicSuffix.txt MagicSuffix
.import misc.txt misc
.import Missiles.txt Missiles
.import MonItemPercent.txt MonItemPercent
.import MonMode.txt MonMode
.import MonName.txt MonName
.import monstats.txt monstats
.import monstats2.txt monstats2
.import MonType.txt MonType
.import npc.txt npc
.import objects.txt objects
.import objgroup.txt objgroup
.import ObjMode.txt ObjMode
.import ObjType.txt ObjType
.import Overlay.txt Overlay
.import PlayerClass.txt PlayerClass
.import PlrMode.txt PlrMode
.import PlrType.txt PlrType
.import Properties.txt Properties
.import qualityitems.txt qualityitems
.import RarePrefix.txt RarePrefix
.import RareSuffix.txt RareSuffix
.import Runes.txt Runes
.import SetItems.txt SetItems
.import shrines.txt shrines
.import skills.txt skills
.import SoundEnviron.txt SoundEnviron
.import Sounds.txt Sounds
.import states.txt states
.import StorePage.txt StorePage
.import SuperUniques.txt SuperUniques
.import TreasureClass.txt TreasureClass
.import TreasureClassEx.txt TreasureClassEx
.import UniqueAppellation.txt UniqueAppellation
.import UniqueItems.txt UniqueItems
.import UniquePrefix.txt UniquePrefix
.import UniqueSuffix.txt UniqueSuffix
.import UniqueTitle.txt UniqueTitle
.import WeaponClass.txt WeaponClass
.import weapons.txt weapons
